# Data settings
data_dir: datasets/LIDC
batch_size: 4
num_workers: 2

# Model architecture
latent_dims:
  - 3
  - 2
  - 1
  
channels_per_block:
  - 16
  - 32
  - 64
  - 128
  - 256
num_classes: 2
activation_fn: relu
convs_per_block: 3
blocks_per_level: 3

# Loss parameters
loss_kwargs:
  type: geco
  top_k_percentage: 0.02
  deterministic_top_k: false
  kappa: 0.05
  decay: 0.99
  rate: 0.01

# Training settings
learning_rate: 0.0001
num_epochs: 100
validation:
  n_batches: 10
exp_dir: experiments/hpu_net
save_every_n_epochs: 10
cuda_visible_devices: '0'